### ISSUE TITLE
Warning: unable to find a suitable fs in /proc/mounts, is it mounted?

### ISSUE THREAD

**Issue by BR0kEN-** [solita/docker-systemd#11]
The `aa-complain /usr/sbin/mysqld` inside of a container ends with:

```
root@cikit01:~# aa-complain /usr/sbin/mysqld
Setting /usr/sbin/mysqld to complain mode.

ERROR: Cache read/write disabled: interface file missing. (Kernel needs AppArmor 2.4 compatibility patch.)
Warning: unable to find a suitable fs in /proc/mounts, is it mounted?
Use --subdomainfs to override.
```

Host and guest - Ubuntu 16.04.2 LTS.

The command for creating a container:

```
    docker run \
      -d \
      -h "cikit01.example.com" \
      -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
      --name "cikit01" \
      --tmpfs /run \
      --tmpfs /run/lock \
      --security-opt seccomp=unconfined \
      -p 2201:22 \
      solita/ubuntu-systemd
```

```
root@brbr:~# docker --version
Docker version 17.06.0-ce, build 02c1d87
```

**Comment by BR0kEN-** [comment]
So, the problem is that `securityfs` isn't mounted. @noidi, do you know whether it should be?

**Comment by noidi** [comment]
I have no experience with AppArmor, but I did a bit of googling and running AppArmor inside a Docker container [seems to be problematic](https://stackoverflow.com/a/27029610/13340). Here's [a related issue](https://github.com/jeroen/RAppArmor/issues/21).

Perhaps you could move the AppArmor stuff out of the container and [provide the AppArmor profile when you start the container](https://docs.docker.com/engine/security/apparmor/)?
