### ISSUE TITLE
Failed to create bus connection

### ISSUE THREAD

**Issue by damianoneill** [solita/docker-systemd#12]
Host OS is OSX, running Docker for OSX. 

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G1212

$ docker --version
Docker version 17.12.0-ce, build c97c6d6
```

If I run the command from your example 

```
docker run -d --name systemd --security-opt seccomp=unconfined --tmpfs /run --tmpfs /run/lock -v /sys/fs/cgroup:/sys/fs/cgroup:ro -t solita/ubuntu-systemd
```

Then 

```
docker exec -it systemd /bin/sh
# timedatectl status
Failed to create bus connection: No such file or directory
```

The same scenario works fine with a centos image running systemd. 

Thanks in advance for your help with this. 
Damian.

**Comment by noidi** [comment]
Hi Damian,

Unfortunately I don't have any ideas about what could be causing that error. I don't use this image anymore, but if you find a way to fix the problem, I'd be happy to merge the fix and credit you as a contributor.

**Comment by damianoneill** [comment]
@noidi looks like dbus is missing from the base image.   

```
apt-get install dbus
```

works fine.  

```
# timedatectl status
      Local time: Mon 2018-02-26 13:25:10 UTC
  Universal time: Mon 2018-02-26 13:25:10 UTC
        RTC time: n/a
       Time zone: n/a (UTC, +0000)
 Network time on: no
 NTP synchronized: no
 RTC in local TZ: no
```

Not sure if you should add it or not, up to yourself, if not maybe a comment in the README?

Thanks,
Damian.

**Comment by damianoneill** [comment]
@noidi fyi, I came to your image through molecule your base is provided as an example for ubuntu with systemd in containers.  See here http://molecule.readthedocs.io/en/latest/examples.html

**Comment by noidi** [comment]
Thanks for debugging the issue and mentioning Molecule, I had not heard of it before.

I guess adding dbus would make sense given the virtual-machine-ish nature of the image.

**Comment by damianoneill** [comment]
Agreed, if you can do that it will add a small amount of space, but make image more useful.  On our side we wont have to inherit and build our own.

**Comment by Jiangxiaochen** [comment]
Thanks for your answer, it works fo me in ubt16.04.
