### ISSUE TITLE
Support for Bionic 18.04

### ISSUE THREAD

**Issue by jeroenvermeulen** [solita/docker-systemd#16]
We love your Docker image, we use it daily for our test builds.
We are already testing on Ubuntu Bionic 18.04, do you plan to create an 18.04 image?

**Comment by noidi** [comment]
This image is not under active development, but I'd be happy to merge (into a new branch) a pull request that adds support for 18.04 and set up a new build for it on Docker Hub.

**Comment by noidi** [comment]
Resolved by #18, merged in 5367cf52c6d6403a27294736924804682461e201.
