### ISSUE TITLE
How to set seccomp to unconfined while starting docker service ?

### ISSUE THREAD

**Issue by chakravarthy392** [solita/docker-systemd#17]
ARCH : S390X
OS : SLES 12 SP2

I am getting the below error while creating container on SLES using docker-18.03 installed from [static binary](https://download.docker.com/linux/static/stable/s390x/).

**"docker: Error response from daemon: OCI runtime create failed: container_linux.go:265: starting container process caused "seccomp: config provided but seccomp not supported": unknown.
"**

I have installed `libseccomp` dependency and able to create a container by including `--security-opt seccomp=unconfined` while executing docker run command, but I want to disable seccomp while initializing the docker service itself. 

I have tried to do it by passing the same parameter to docker service file but could not start the docker. Please let me know if there is any way.

**Comment by noidi** [comment]
I'm sorry, I don't understand how your problem is related to this image. If I understood correctly, you are having trouble configuring your Docker daemon. I don't have any experience with SLES so I don't think I can help you there.
