### ISSUE TITLE
cgroup location?

### ISSUE THREAD

**Issue by JihoYoo7** [solita/docker-systemd#19]
Hi, when I try to set up the cgroup hierarchy in amazon linux(EC2 example), it does not work. It outputs mkdir: cannot create directory '/host/sys/fs/cgroup/systemd': No such file or directory. And I realized that cgroup is not under /host/sys/fs and rather just /cgroups. How do I change the run command so it works on EC2 amazon linux?

**Comment by noidi** [comment]
The easiest solution would be to use Amazon Linux 2, as it comes with systemd and sets up the cgroups properly.

If that's not an option for you, you could edit [the setup script](https://github.com/solita/docker-systemd/blob/master/setup) and change the path there. Note that you also need to change the bind mounts in the `docker run` command: `-v /sys/fs/cgroup:/sys/fs/cgroup:ro` would become `-v /cgroups:/sys/fs/cgroup:ro`.
