### ISSUE TITLE
Support Docker for Mac and Docker for Windows

### ISSUE THREAD

**Issue by noidi** [solita/docker-systemd#4]
Add support for Docker for Mac and Docker for Windows.

**Comment by noidi** [comment]
@deiga I've moved the [Docker host setup](https://github.com/solita/docker-systemd#setup) into a privileged container. From Docker for Mac's documentation I gather that the setup script now has a good chance of working there as well. If you give it a try, please let me know if it really works! :) (Also note the [known issues](https://github.com/solita/docker-systemd#known-issues) with the Ubuntu image on Docker < 1.12.0)

**Comment by rectalogic** [comment]
docker-systemd works with Docker for Mac for me.
