### ISSUE TITLE
Update instruction seccomp=unconfined to seccomp:unconfined

### ISSUE THREAD

**Issue by jcrben** [solita/docker-systemd#7]
In the instruction under Testing at https://hub.docker.com/r/solita/ubuntu-systemd/ there is the following:
`docker run -d --name systemd --security-opt seccomp=unconfined --stop-signal=SIGRTMIN+3 --tmpfs /run --tmpfs /run/lock -v /sys/fs/cgroup:/sys/fs/cgroup:ro -t solita/ubuntu-systemd`

That `seccomp=unconfined` should be updated to `seccomp:unconfined` - see e.g. https://github.com/docker/docker/issues/24810

**Comment by noidi** [comment]
If I understood correctly, `seccomp=unconfined` is the new syntax preferred in Docker 1.11 and newer, and `seccomp:unconfined` is needed only with Docker 1.10 and older.

I would like to keep the instructions in line with Docker's current documentation, so I'm inclined to leave the syntax as `seccomp=undefined`. I also can't promise that this project will remain backwards compatible with Docker 1.10, so future versions of the image may not work anyway regardless of command-line syntax.

Thank you for the report! I hope this issue will work as documentation for people who still need to run this image on 1.10.

**Comment by jcrben** [comment]
Ah, good point, somehow I reversed that and thought I was running the updated docker...
